apiVersion: v1
kind: Service
metadata:
  name: ytAPI-service
spec:
  selector:
    app: ytAPI
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31110
